USER_NAME_MIN_LENGTH = 3
USER_NAME_MAX_LENGTH = 15
USER_DISPLAY_NAME_MIN_LENGTH = 3
USER_DISPLAY_NAME_MAX_LENGTH = 30
USER_ROLE_ADMIN = 'admin'
USER_ROLE_USER = 'user'

HEADER_AUTH_TOKEN = 'Authorization'

AUTH_TOKEN_TIME_LENGTH = 1.month.from_now

COLLECTION_LABEL = 'collection'
DEFAULT_PAGE_SIZE = 999999
MINIMUM_PAGE_SIZE = 1
MAXIMUM_PAGE_SIZE = 999999

DEFAULT_SORT_BY = :created_at
DEFAULT_SORT_ORDER = :asc